package me.newburyminer.customItems.entity

enum class EntityComponentType {

    ELYTRA_BREAKER_SHOOTER,
    ELYTRA_BREAKER_FIREWORK,
    LAVA_ON_DEATH,
    PROJECTILE_DAMAGE_SHOOTER,
    CUSTOM_DAMAGE_PROJECTILE,
    HOMING_PROJECTILE_SHOOTER,
    HOMING_PROJECTILE,
    EXPLOSIVE_PROJECTILE_SHOOTER,
    EXPLOSIVE_PROJECTILE,
    CUSTOM_EXPLOSION_CREEPER,
    POTION_EXPLOSION_CREEPER,
    FIREBOMB_CREEPER,
    ARROWBOMB_CREEPER,
    FIREWORK_CREEPER,
    TNT_HEAD_CREEPER,
    TNT_HEAD_TNT,
    MELEE_CUSTOM_HIT,
    CUSTOM_WITCH_POTION,
    CANCEL_PROJECTILES,
    DEFAULT_ENTITY_COMPONENT,

}