package me.newburyminer.customItems.entity

enum class EntityComponentType {

    ELYTRA_BREAKER_SHOOTER,
    ELYTRA_BREAKER_FIREWORK,
    LAVA_ON_DEATH,
    CUSTOM_DAMAGE,
    PROJECTILE_DAMAGE_SHOOTER,
    HOMING_PROJECTILE_SHOOTER,
    HOMING_PROJECTILE,
    EXPLOSIVE_PROJECTILE_SHOOTER,
    EXPLOSIVE_PROJECTILE,


}