package me.newburyminer.customItems.items

enum class CustomItem(val cds: Array<String> = arrayOf(), var realName: String = "", val stackable: Boolean = false) {
    ALL,
    JERRY_IDOL,
    VILLAGER_ATOMIZER,
    VILLAGER,
    GOLDEN_ZOMBIE,
    FANGED_STAFF(arrayOf("Fangs", "Vexing")),
    TOTEM_CORE(stackable = true),
    FLETCHER_UPGRADE,
    DRIPSTONE_ARROW(stackable = true),
    ENDER_PEARL_ARROW(stackable = true),
    WITHER_SKULL_ARROW(stackable = true),
    LLAMA_SPIT_ARROW(stackable = true),
    SHULKER_BULLET_ARROW(stackable = true),
    WIND_HOOK(arrayOf("")),
    INPUT_DEVICES,
    MINECART_MATERIALS,
    ACTUAL_REDSTONE,
    CONTAINERS,
    REDSTONE_AMALGAMATION,
    REDSTONE_REPEATER,
    POLARIZED_MAGNET,
    LAST_PRISM(arrayOf("Beam", "Zap")),
    MULTI_LOAD_CROSSBOW,
    VEINY_PICKAXE(arrayOf("")),
    TREECAPITATOR,
    EXCAVATOR,
    PEW_MATIC_HORN(arrayOf("")),
    TRADING_SCRAMBLER,
    EXPERIENCE_FLASK,
    NETHERITE_MULTITOOL,
    HOEVEL,
    AXEPICK,
    NETHERITE_MATTOCK,
    POCKETKNIFE_MULTITOOL,
    HOE,
    HOOKED_CUTLASS,
    AXE_OF_PEACE,
    ENDER_BLADE(arrayOf("")),
    HEAVY_GREATHAMMER,
    CRESTED_DAGGER,
    FIERY_SHARD(stackable = true),
    MYSTICAL_GREEN_APPLE(stackable = true),
    ENDER_NODE,
    SOUL_CRYSTAL(stackable = true),
    NETHERITE_COATING(stackable = true),
    WITHER_COATING(stackable = true),
    REINFORCING_STRUTS(stackable = true),
    SHULKER_FRUIT,
    WARDEN_SPAWNER(stackable = true),
    WITHER_SPAWNER(stackable = true),
    BASTION_SPAWNER(stackable = true),
    MONUMENT_SPAWNER(stackable = true),
    DESERT_SPAWNER(stackable = true),
    SURFACE_TO_AIR_MISSILE(arrayOf("")),
    TRIPLE_SWIPE_SWORD(arrayOf("")),
    WIND_CHARGE_CANNON(arrayOf("")),
    SNIPER_RIFLE(arrayOf("")),
    GRAVITY_HAMMER(arrayOf("")),
    RIDABLE_CROSSBOW(arrayOf("")),
    LANDMINE_LAUNCHER(arrayOf("")),
    MOON_BOOTS,
    COWBOY_HAT,
    DOUBLE_JUMP_BOOTS(arrayOf("")),
    TURTLE_SHELL(arrayOf("")),
    DRINKING_HAT,
    HERMESS_TROUSERS,
    SHADOW_LEGS(arrayOf("")),
    BERSERKER_CHESTPLATE,
    XRAY_GOGGLES(arrayOf("")),
    REPELLANT_PANTS,
    MACE_SHIELDED_PLATING,
    MOLTEN_CHESTPLATE,
    TOOLBELT,
    CLOUD_BOOTS,
    INVISIBILITY_CLOAK,
    AQUEOUS_SANDALS(arrayOf("")),
    ENCRUSTED_PANTS,
    WELDING_HELMET,
    ANTI_VENOM_SHIRT,
    ENERGY_RESTORING_PANTS,
    STABILZING_SNEAKERS,
    JETPACK_CONTROLLER_SET,
    JETPACK,
    JETPACK_CONTROLLER,
    HARD_HAT,
    STEEL_TOED_BOOTS,
    ASSASSINS_HOOD,
    ASSASSINS_ROBE,
    ASSASSINS_LEGGINGS,
    ASSASSINS_LOAFERS,
    WARRIOR_HELM,
    WARRIOR_CHESTPLATE(arrayOf("")),
    WARRIOR_GREAVES,
    WARRIOR_BOOTS,
    MINERS_HELM,
    TRACKING_COMPASS,
    REINFORCED_CAGE,
    DARK_STEEL_RAPIER(arrayOf("")),
    FROZEN_SHARD(arrayOf("")),
    BARBED_BLADE(arrayOf("")),
    SONIC_CROSSBOW(arrayOf("")),
    DUAL_BARRELED_CROSSBOW,
    MECHANIZED_ELYTRA(arrayOf("Boost")),
    WARDEN_HEART(stackable = true),
    FRAGMENT_OF_SOUND(stackable = true),
    WARDEN_CARAPACE(stackable = true),
    SHADOW_DISC_CORE(stackable = true),
    REDSTONE_BOX,
    REFRESHING_EMERALD,
    DYE_PALETTE(stackable = true),
    MEGAMIX_DISC_TRACK(stackable = true),
    GALE_BLADE(arrayOf("")),
    PORTABLE_CANNON(arrayOf("")),
    CONDENSED_DEEPSLATE(stackable = true),
    CONDENSED_INVISIBILITY(stackable = true),
    CLOUD_FRAGMENT(stackable = true),
    CLERIC_UPGRADE,
    ENCHANTED_CATALYST(stackable = true),
    ENRICHED_FEATHER(stackable = true),
    TOOL_HANDLE(stackable = true),
    REINFORCED_HANDLE(stackable = true),
    TOOLSMITH_UPGRADE,
    ARMORSMITH_UPGRADE,
    STEEL_PLATING(stackable = true),
    FIRE_RESISTANT_RESIN(stackable = true),
    CONDENSED_ICE(stackable = true),
    HANDLE_BINDING(stackable = true),
    STRENGTHENING_RODS(stackable = true),
    STEEL_CHUNK(stackable = true),
    MOLTEN_MIXTURE(stackable = true),
    MAGICAL_FLASK(stackable = true),
    LIGHTWEIGHT_AMALGAMATION(stackable = true),
    RPG_LAUNCHER(arrayOf("")),


    /*
    TEST2(1, 0),
    REINFORCED_IRON_SWORD(2, 0),
    EATABLE_BLOCK(3, 0),
    WOODCUTTER(4, 0),
    NETHERITE_CHESTPLATE(5, 0),
    VERY_ENCHANT(6, 0),
    POT(7, 0),
    FIRE(8, 0),
    OMMY(9, 0),
    VILLAG_A(10, 1),*/
    ;

    val id: Int
        get() {
            return this.ordinal
        }

    init {
        var newName = ""
        for (word in this.name.split("_")) {
            var newWord = word.lowercase()
            newWord = newWord[0].uppercase() + if (newWord.length > 1) newWord.substring(1) + " " else " "
            newName += newWord
        }
        newName = newName.substring(0, newName.lastIndex)
        this.realName = newName
    }

    fun getCooldown(order: String = ""): String {
        return this.name + "_" + order
    }
}